version: 2.1

commands:
  check_python:
    steps:
      - run:
          name: check Python
          command: |
            which python
            python --version
      - run:
          name: check Pip
          command: |
            which pip
            pip --version
       - run:
          name: check pyenv
          command: |
            which pyenv || true
  setup_python_env:
    parameters:
      cache-key:
        type: string
        default: venv-v1
    description: Setup Python env
    steps:
    - restore_cache:
        name: Restoring VENV Cache
        key: << parameters.cache-key >>-{{ checksum "data-pipelines/requirements.txt" }}
    - run:
        name: Setup Python venv
        command: |
          make setup
    - save_cache:
        name: Saving VENV Cache
        key: << parameters.cache-key >>-{{ checksum "data-pipelines/requirements.txt" }}
        paths:
        - ./venv

jobs:
  install:
    parameters:
      img: string    
    docker:
      - image: << parameters.img >>
    steps:
      - checkout
      - check_python
      - run: |
          make venv/bin/activate
      - run:
          name: install deps
          command: |
            . venv/bin/activate; pip install pre-commit
            pip list --verbose
  inspect:
    parameters:
      img:
        type: string
    docker:
      - image: << parameters.img >>
    resource_class: small
    steps:
      - checkout
      - check_python
      - setup_python_env:
          # force cimg/python:3.7 to use a cache from circleci/python:3.7
          cache-key: circleci/python:3.7
      - run:
          name: check deps
          command: |
            source ./venv/bin/activate
            pip list
            
workflows:
  diff:
    jobs:
      - install:
          matrix:
            parameters:
              img:
                - cimg/python@sha256:f90d693d4a067ed5bceb970aef66da005198b3cba34dc0615c72645d50ad95ae
                - cimg/python@sha256:845ede0b8a80d2d961b9f5cecb00261a3b4d6152ddf66eae6f575ee3663bda05
#   snakecharm:
#     jobs:
#       - inspect:
#           matrix:
#             parameters:
#               img:
#                 # - circleci/python:3.7
#                 - cimg/python:3.7
