version: 2.1

commands:
  setup_python_env:
    description: Setup Python env
    steps:
    - restore_cache:
        name: Restoring VENV Cache
        key: venv-v1-{{ checksum "data-pipelines/requirements.txt" }}
    - run:
        name: Setup Python venv
        command: |
          make setup
    - save_cache:
        name: Saving VENV Cache
        key: venv-v1-{{ checksum "data-pipelines/requirements.txt" }}
        paths:
        - ./venv

jobs:
  inspect:
    parameters:
      img:
        type: string
    docker:
      - image: << parameters.img >>
    resource_class: small
    steps:
      - run:
          name: check Python
          command: |
            which python
            python --version
      - run:
          name: check Pip
          command: |
            which pip
            pip --version
      - run:
          name: check pyenv
          command: |
            which pyenv || true
      - setup_python_env
      - run:
          name: check deps
          command: |
            source ./venv/bin/activate
            pip list
            
workflows:
  snakecharm:
    jobs:
      - inspect:
          matrix:
            parameters:
              img:
                - circleci/python:3.7
                - cimg/python:3.7
